ifeq ($(OS),Windows_NT)
PYTHON ?= .venv/Scripts/python.exe
else
PYTHON ?= .venv/bin/python
endif

ALEMBIC_CONFIG ?= alembic.ini
override ENV_FILE := .env

ifneq (,$(wildcard $(ENV_FILE)))
include $(ENV_FILE)
export
endif

.DEFAULT_GOAL := help

.PHONY: help require-env alembic alembic-current alembic-history alembic-upgrade alembic-downgrade alembic-downgrade-one alembic-downgrade-base alembic-revision

help:
	@echo "Available commands:"
	@echo "  make alembic-current             - Show current database revision."
	@echo "  make alembic-history             - Show migration history."
	@echo "  make alembic-upgrade             - Upgrade database to head."
	@echo "  make alembic-upgrade rev=REV     - Upgrade database to a specific revision."
	@echo "  make alembic-downgrade rev=REV   - Downgrade database to a specific revision (e.g. rev=-1)."
	@echo "  make alembic-downgrade-one       - Downgrade database by one revision."
	@echo "  make alembic-downgrade-base      - Downgrade database to base revision."
	@echo "  make alembic-revision m=\"msg\"    - Create an autogenerated migration."
	@echo "  make alembic cmd=\"heads\"         - Run any Alembic command."

require-env:
	@test -f "$(ENV_FILE)" || { echo "Missing $(ENV_FILE). Create it with POSTGRES_* connection variables."; exit 1; }

alembic: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) $(cmd)

alembic-current: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) current

alembic-history: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) history

alembic-upgrade: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) upgrade $(or $(rev),head)

alembic-downgrade: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) downgrade $(rev)

alembic-downgrade-one: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) downgrade -1

alembic-downgrade-base: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) downgrade base

alembic-revision: require-env
	$(PYTHON) -m alembic -c $(ALEMBIC_CONFIG) revision --autogenerate -m "$(m)"
