"""initial_schema

Revision ID: 65d22d5122aa
Revises: 
Create Date: 2026-05-29 16:06:29.297161
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_sources_name'), 'application_sources', ['name'], unique=True)
    op.create_table('application_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_tags_kind'), 'application_tags', ['kind'], unique=False)
    op.create_index(op.f('ix_application_tags_name'), 'application_tags', ['name'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('document_type', sa.Enum('CV', 'COVER_LETTER', 'PORTFOLIO', 'OTHER', name='document_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_documents_file_name'), 'documents', ['file_name'], unique=False)
    op.create_table('feature_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=2000), nullable=False),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('screenshot_data_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_memories_closed_at'), 'feature_memories', ['closed_at'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=True)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('application_source_id', sa.Integer(), nullable=True),
    sa.Column('primary_document_id', sa.Integer(), nullable=True),
    sa.Column('position_title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('sent_cv', 'recruiter_call', 'receive_response', 'interview_scheduled', 'interview_finished', 'offer', 'rejected', name='application_status'), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('position_url', sa.String(length=1000), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('seniority', sa.String(length=100), nullable=True),
    sa.Column('contact_url', sa.String(length=1000), nullable=True),
    sa.Column('contact_description', sa.Text(), nullable=True),
    sa.Column('recruitment_description', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_position_text', sa.Text(), nullable=True),
    sa.Column('raw_position_source', sa.String(length=50), nullable=True),
    sa.Column('expected_salary_min_pln', sa.Integer(), nullable=True),
    sa.Column('expected_salary_max_pln', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_source_id'], ['application_sources.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['primary_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_applied_at'), 'job_applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_job_applications_company_id'), 'job_applications', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_applications_last_update_at'), 'job_applications', ['last_update_at'], unique=False)
    op.create_index(op.f('ix_job_applications_position_title'), 'job_applications', ['position_title'], unique=False)
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    op.create_table('application_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('update_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_updates_application_id'), 'application_updates', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_updates_occurred_at'), 'application_updates', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_application_updates_update_type'), 'application_updates', ['update_type'], unique=False)
    op.create_table('job_application_tags',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['application_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_application_tags')
    op.drop_index(op.f('ix_application_updates_update_type'), table_name='application_updates')
    op.drop_index(op.f('ix_application_updates_occurred_at'), table_name='application_updates')
    op.drop_index(op.f('ix_application_updates_application_id'), table_name='application_updates')
    op.drop_table('application_updates')
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_position_title'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_last_update_at'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_company_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_applied_at'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_feature_memories_closed_at'), table_name='feature_memories')
    op.drop_table('feature_memories')
    op.drop_index(op.f('ix_documents_file_name'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_application_tags_name'), table_name='application_tags')
    op.drop_index(op.f('ix_application_tags_kind'), table_name='application_tags')
    op.drop_table('application_tags')
    op.drop_index(op.f('ix_application_sources_name'), table_name='application_sources')
    op.drop_table('application_sources')
    # ### end Alembic commands ###
